# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
    - task build
    - task deploy
  build:
    cmds:
    - sam build --cached
  deploy:
    cmds:
    - sam deploy --no-confirm-changeset
  delete:
    cmds:
    - aws cloudformation delete-stack --stack-name potential-fiesta
