# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
    - task cloudbuild
  cloudbuild:
    cmds:
    - gcloud builds submit
  terraform:
    dir: terraform
    cmds:
    - terraform fmt
    - terraform validate
    - terraform apply -auto-approve
  build:
    cmds:
    - docker build -t front .
  run:
    cmds:
    - docker run --env-file .env --publish 8080:8080 front
